name: Github Work Auto build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "0 0 ? * ? "
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: 'Initialize Environment'
        run: sudo apt-get update -q && sudo apt-get install -y --no-install-recommends build-essential curl git \
              cc-aarch64-linux-gnu python3-dev python3-venv cmake ninja-build \
              device-tree-compiler libxml2-utils libclang-dev python3-pexpect
      - run: pip --help
