name: Github Work Auto build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "0 0 ? * ? "
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: 'Initialize Environment'
        run: apt-get update -q && apt-get install -y --no-install-recommends \
              build-essential \
              curl \
              git \
              # for seL4
              gcc-aarch64-linux-gnu \
              python3-dev \
              python3-venv \
              cmake \
              ninja-build \
              device-tree-compiler \
              libxml2-utils \
              # for bindgen
              libclang-dev \
              # for test script
              python3-pexpect
      - run: pip --help
