name: Github Work Auto build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: "0 0 ? * ? "
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Environments
        run: sudo apt install docker
      - run: docker build --build-arg UID=`id -u` --build-arg GID=`id -g` -t auto-build .
      - run: docker run -d --name rel4-autobuild -v .:/work:z auto-build bash ./build.sh
